# Generated by Django 3.1.2 on 2020-11-20 17:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='github',
            field=models.CharField(max_length=500, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.CharField(max_length=500, validators=[django.core.validators.URLValidator()]),
        ),
    ]
