# Generated by Django 3.1.7 on 2021-03-16 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0005_auto_20201229_0136'),
        ('software', '0003_collaborators_project_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDetails',
            fields=[
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='software.project')),
                ('release_date', models.CharField(max_length=8)),
                ('status', models.CharField(max_length=50)),
                ('technical_description', models.TextField()),
                ('contributions', models.TextField()),
                ('collaborators', models.ManyToManyField(to='software.Collaborators')),
                ('screenshots', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.album')),
            ],
        ),
        migrations.DeleteModel(
            name='Project_Details',
        ),
    ]
