# Generated by Django 3.1.7 on 2023-02-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_event_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.FloatField(default=1.3),
        ),
    ]
