# Generated by Django 3.1.7 on 2023-02-28 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_event_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='duration',
        ),
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
