# Generated by Django 3.1.7 on 2024-03-08 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20240305_0423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ep',
            old_name='artwiork',
            new_name='artwork',
        ),
        migrations.RemoveField(
            model_name='song',
            name='flyer',
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='flyer',
            field=models.ImageField(blank=True, null=True, upload_to='flyer'),
        ),
    ]
