# Generated by Django 3.1.7 on 2024-03-08 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_auto_20240308_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('soundcloud', models.URLField(blank=True, null=True)),
                ('spotify', models.URLField(blank=True, null=True)),
                ('apple_music', models.URLField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='ep',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='song',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='song',
            name='file',
        ),
        migrations.AddField(
            model_name='ep',
            name='amazon',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ep',
            name='apple',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ep',
            name='bandcamp',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ep',
            name='presave',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ep',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ep',
            name='soundcloud',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ep',
            name='spotify',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ep',
            name='tidal',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ep',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='artists',
            field=models.ManyToManyField(blank=True, related_name='events', to='music.Artist'),
        ),
        migrations.AddField(
            model_name='song',
            name='artists',
            field=models.ManyToManyField(blank=True, related_name='songs', to='music.Artist'),
        ),
    ]
