# Generated by Django 3.1.7 on 2024-03-08 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_auto_20240308_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='ep',
            name='artists',
            field=models.ManyToManyField(blank=True, related_name='songs', to='music.Artist'),
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
