# Generated by Django 3.1.7 on 2025-08-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_auto_20240308_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='spotify',
        ),
        migrations.RemoveField(
            model_name='ep',
            name='spotify',
        ),
        migrations.AddField(
            model_name='artist',
            name='bandcamp',
            field=models.URLField(blank=True, null=True),
        ),
    ]
