# Generated by Django 3.1.2 on 2020-12-29 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared', '0005_auto_20201229_0136'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecreteLetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('argument', models.TextField()),
                ('link_to_soundcloud', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=8)),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.image')),
            ],
        ),
    ]
