# Generated by Django 3.1.2 on 2020-11-20 21:54

from django.db import migrations, models
import shared.models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0003_auto_20201120_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='length',
        ),
        migrations.RemoveField(
            model_name='image',
            name='width',
        ),
        migrations.AddField(
            model_name='image',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
