# Generated by Django 3.1.7 on 2023-02-27 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0005_auto_20201229_0136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['name']},
        ),
    ]
