# Generated by Django 3.1.7 on 2023-03-01 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0007_links'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Links',
            new_name='Link',
        ),
    ]
