# Generated by Django 3.1.2 on 2020-11-20 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0003_auto_20201120_1930'),
        ('photography', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='album',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shared.album'),
            preserve_default=False,
        ),
    ]
